language: ruby
rvm:
  - 2.0.0-p247

sudo: false

before_script:
  - echo 'America/Chicago' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sudo ntpdate ntp.ubuntu.com

install: bundle install --without development --deployment
cache:
  directories:
  - vendor/bundle

services:
- mongodb
- redis-server
